import { toPng, toSvg } from 'html-to-image'
import { useCallback, useEffect, useRef, useState } from 'react'
import { addChild, addRoot, addSibling, deleteSubtree, emptyDocument, expandAncestors, hasChildren, moveNode, renameNode, toggleCollapsed } from './model/operations'
import type { MindMapDocument, Point } from './model/types'
import { parseDocument } from './model/validation'
import { commit, createHistory, redo, undo } from './state/mindMapStore'
import { loadDocument, saveDocument } from './storage/localStorage'
import MindMapCanvas from './components/MindMapCanvas'
import SearchPanel from './components/SearchPanel'
import ShortcutHelp from './components/ShortcutHelp'
import Toolbar from './components/Toolbar'

const MAX_IMPORT_BYTES = 1_000_000
function download(name: string, data: string, type = 'application/json') { const url = URL.createObjectURL(new Blob([data], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 0) }

export default function App() {
  const initial = useRef(loadDocument())
  const [history, setHistory] = useState(() => createHistory(initial.current.document))
  const [selectedId, setSelectedId] = useState<string>()
  const [search, setSearch] = useState('')
  const [message, setMessage] = useState(initial.current.warning ?? '')
  const [centerSignal, setCenterSignal] = useState(0)
  const [deletingId, setDeletingId] = useState<string>()
  const inputRef = useRef<HTMLInputElement>(null)
  const surfaceRef = useRef<HTMLDivElement>(null)
  const documentMap = history.present
  const mutate = useCallback((operation: (current: MindMapDocument) => MindMapDocument) => { try { setHistory((current) => { const next = operation(current.present); return next === current.present ? current : commit(current, next) }) } catch (error) { setMessage(error instanceof Error ? error.message : 'That action could not be completed.') } }, [])
  useEffect(() => { const warning = saveDocument(documentMap); if (warning) setMessage(warning) }, [documentMap])
  const rename = useCallback((id: string, label: string) => mutate((current) => renameNode(current, id, label)), [mutate])
  const remove = useCallback((id: string) => { if (hasChildren(documentMap, id)) setDeletingId(id); else { mutate((current) => deleteSubtree(current, id)); setSelectedId(undefined) } }, [documentMap, mutate])
  useEffect(() => { const shortcut = (event: KeyboardEvent) => { const tag = (event.target as HTMLElement | null)?.tagName; if (tag === 'INPUT' || tag === 'TEXTAREA') return; const modifier = event.metaKey || event.ctrlKey; if (modifier && event.key.toLowerCase() === 'z') { event.preventDefault(); setHistory((state) => event.shiftKey ? redo(state) : undo(state)); return } if (modifier && event.key.toLowerCase() === 'y') { event.preventDefault(); setHistory((state) => redo(state)); return } if (!selectedId) return; if (event.key === 'Tab') { event.preventDefault(); mutate((current) => addChild(current, selectedId)); return } if (event.key === 'Enter') { event.preventDefault(); mutate((current) => addSibling(current, selectedId)); return } if (event.key === 'Delete' || event.key === 'Backspace') { event.preventDefault(); remove(selectedId) } }; window.addEventListener('keydown', shortcut); return () => window.removeEventListener('keydown', shortcut) }, [mutate, remove, selectedId])
  const importFile = () => inputRef.current?.click()
  const readImport = (file?: File) => { if (!file) return; if (file.size > MAX_IMPORT_BYTES) { setMessage('Import rejected: files must be 1 MB or smaller.'); return } const reader = new FileReader(); reader.onload = () => { const result = parseDocument(typeof reader.result === 'string' ? reader.result : ''); if (!result.ok) { setMessage(`Import rejected: ${result.error}`); return } setHistory(createHistory(result.value)); setSelectedId(undefined); setMessage('Mind map imported.'); setCenterSignal((value) => value + 1) }; reader.onerror = () => setMessage('The selected file could not be read.'); reader.readAsText(file) }
  const exportImage = async () => { if (!surfaceRef.current) return; try { const data = await toPng(surfaceRef.current, { pixelRatio: 2, backgroundColor: getComputedStyle(document.body).backgroundColor }); const link = document.createElement('a'); link.href = data; link.download = 'mindmap.png'; link.click() } catch { try { const svg = await toSvg(surfaceRef.current); download('mindmap.svg', svg, 'image/svg+xml'); setMessage('PNG export was unavailable; an SVG fallback was downloaded.') } catch { setMessage('Image export failed. JSON export is still available.') } } }
  return <main className="app-shell"><header><div><p className="eyebrow">Local-first editor</p><h1>Mindmap Panel</h1></div><SearchPanel document={documentMap} value={search} onChange={setSearch} onPick={(id) => { mutate((current) => expandAncestors(current, id)); setSelectedId(id); setCenterSignal((value) => value + 1) }} /></header><Toolbar canUndo={history.past.length > 0} canRedo={history.future.length > 0} hasSelection={Boolean(selectedId)} onAddRoot={() => mutate((current) => addRoot(current))} onAddChild={() => selectedId && mutate((current) => addChild(current, selectedId))} onAddSibling={() => selectedId && mutate((current) => addSibling(current, selectedId))} onDelete={() => selectedId && remove(selectedId)} onUndo={() => setHistory(undo)} onRedo={() => setHistory(redo)} onCenter={() => setCenterSignal((value) => value + 1)} onNew={() => { if (window.confirm('Start a new blank mind map?')) { setHistory(createHistory(emptyDocument())); setSelectedId(undefined) } }} onClear={() => { if (window.confirm('Clear every node from this mind map?')) { setHistory(createHistory(emptyDocument())); setSelectedId(undefined) } }} onImport={importFile} onExportJson={() => download('mindmap.json', JSON.stringify(documentMap, null, 2))} onExportImage={() => void exportImage()} /><input ref={inputRef} className="sr-only" type="file" accept="application/json,.json" onChange={(event) => { readImport(event.target.files?.[0]); event.target.value = '' }} /><div ref={surfaceRef} className="canvas-surface">{documentMap.nodes.length === 0 ? <section className="empty-state"><h2>Start with one clear idea</h2><p>Create a root node, then use Tab for children and Enter for siblings.</p><button onClick={() => mutate((current) => addRoot(current))}>Create root node</button></section> : <MindMapCanvas document={documentMap} selectedId={selectedId} searchTerm={search} centerSignal={centerSignal} onSelect={setSelectedId} onMove={(id: string, position: Point) => mutate((current) => moveNode(current, id, position))} onRename={rename} onToggleCollapse={(id) => mutate((current) => toggleCollapsed(current, id))} />}</div><ShortcutHelp />{message && <div role="status" className="notice">{message}<button onClick={() => setMessage('')} aria-label="Dismiss message">×</button></div>}{deletingId && <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="delete-title"><h2 id="delete-title">Delete this branch?</h2><p>All descendant ideas will also be removed.</p><footer><button onClick={() => setDeletingId(undefined)}>Cancel</button><button className="danger" onClick={() => { mutate((current) => deleteSubtree(current, deletingId)); setSelectedId(undefined); setDeletingId(undefined) }}>Delete branch</button></footer></section></div>}</main>
}
